services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    environment:
      CGO_ENABLED: 0
      MARIADB_PASSWORD: dev
  mariadb:
    image: mariadb:10.8
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=ReadyWorker
      - MYSQL_USER=readyworker
      - MYSQL_PASSWORD=dev
    volumes: 
      - readyworker-db:/var/lib/mysql
    ports:
      - 3306:3306
