services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      mariadb:
         condition: service_healthy
    environment:
      CGO_ENABLED: 0
      MARIADB_PASSWORD: dev
  mariadb:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: ReadyWorker
      MYSQL_USER: readyworker
      MYSQL_PASSWORD: dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 1s
      timeout: 5s
      start_period: 5s
      retries: 3
    volumes: 
      - readyworker_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  readyworker_db:

