services:
  app:
    build: .
    ports:
      - 0.0.0.0:8080:8080
    depends_on:
      mariadb:
         condition: service_healthy
    environment:
      CGO_ENABLED: 0
      MARIADB_PASSWORD: dev
      JWT_SECRETKEY: dev-readyworker
  mariadb:
    image: mariadb:10.8
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: ReadyWorker
      MYSQL_USER: readyworker
      MYSQL_PASSWORD: dev
    healthcheck:
      test: "/usr/bin/mysql --user=readyworker --password=dev --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 5s
      start_period: 5s
      retries: 3
    volumes: 
      - readyworker_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  readyworker_db:

